#!/bin/sh
SCRIPTDIR=$(dirname "$0")
XYZ_HOME=$(cd "$SCRIPTDIR" && pwd)

getPid() {
  echo $(ps | grep "php -S $1" | grep -v "grep" | cut -d' ' -f1)
}

if [ "$1" = "stop" ]; then

  pid=$(getPid "");
  if [ -z "$pid" ]; then
    echo "No server to stop"
  else
    echo  "Killing sever at pid $pid"
    kill $pid
  fi

elif [ "$1" = "-S" ] || [ "$1" = "start" ]; then

  if [ -z "$2" ]; then
    hostName="localhost:8000"
  else
    hostName="$2"
  fi

  pid=$(getPid "$hostName");

  if [ -z "$pid" ]; then
    echo "Starting server on $hostName"
    php -S "$hostName" "$XYZ_HOME/index.php"
  else
    echo "Server already running under pid $pid."
    echo "Use 'xyz stop' to stop."
  fi
elif [ "$1" = "test" ]; then
  sh "$XYZ_HOME/factory/test.sh"
elif [ "$1" = "build" ]; then
  sh "$XYZ_HOME/factory/build.sh"

else
  prefix=$( echo "$1" |cut -c1 );
  if [ "$prefix" = "-" ] || [ "$prefix" = "/" ]; then
    php -f "$XYZ_HOME/index.php" -- $@
  elif [ -e "$XYZ_HOME/engine/cli/commands/$1.sh" ]; then
    file="$XYZ_HOME/engine/cli/commands/$1.sh"
    shift;
    sh "$file" $@
  else
    #TODO did you mean?
    echo "[!] Unknown command: '$1'."
    exit 1
  fi
fi
